document.write("<ul>")
document.write("<li><a href='./cadastro.html'>cadastro</a></li>")
document.write("<li><a href='./mediadenotas.html'>media de notas</a></li>")
document.write("<li><a href='./imc.html'>IMC</a></li>")
document.write("<li><a href='./calcaumento.html'>Calc aumento</a></li>")
document.write("</ul>")